/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EventoDAO;
import DAO.TipoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.Evento;
import negocio.Tipo;
import util.CaException;

/**
 *
 * @author vanRz
 */
public class CrearEvento extends javax.swing.JFrame {

    /**
     * Creates new form CrearEvento
     */
    public CrearEvento() {
        super("Crear Evento");
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nevento = new javax.swing.JTextField();
        idevento = new javax.swing.JTextField();
        existeCopago = new javax.swing.JComboBox();
        vevento = new javax.swing.JTextField();
        asisMax = new javax.swing.JTextField();
        finicio = new javax.swing.JTextField();
        fcierre = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        inscripcion = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numInscr = new javax.swing.JTextField();
        tipoEvt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lugarEvt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fechaCancel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fmaxInscr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        boxSobrecupo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        obserArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("EVENTOS COOPEUD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 11, -1, -1));

        jLabel2.setText("Datos del evento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 38, -1, -1));

        jLabel3.setText("Nombre del Evento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, -1));

        jLabel4.setText("ID Evento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, -1));

        jLabel5.setText("Tipo :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, -1, -1));

        jLabel6.setText("Copago:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel7.setText("Valor Total del Evento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 74, -1, 20));

        jLabel8.setText("Asistencia Maxima:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel10.setText("Fecha de inicio:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel11.setText("Fecha de Cierre:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        nevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neventoActionPerformed(evt);
            }
        });
        getContentPane().add(nevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 70, 217, 21));
        getContentPane().add(idevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 102, 217, -1));

        existeCopago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "si", "no" }));
        existeCopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existeCopagoActionPerformed(evt);
            }
        });
        getContentPane().add(existeCopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        vevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veventoActionPerformed(evt);
            }
        });
        getContentPane().add(vevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 217, 20));
        getContentPane().add(asisMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 70, -1));

        finicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finicioActionPerformed(evt);
            }
        });
        getContentPane().add(finicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 200, -1));
        getContentPane().add(fcierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, -1));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        inscripcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "si", "no" }));
        getContentPane().add(inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        jLabel13.setText("¿Tiene Inscripcion?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel14.setText("# Inscripciones: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        numInscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numInscrActionPerformed(evt);
            }
        });
        getContentPane().add(numInscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 61, -1));

        tipoEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEvtActionPerformed(evt);
            }
        });
        getContentPane().add(tipoEvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 128, 217, -1));

        jLabel15.setText("Descripcion: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel16.setText("Lugar:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        getContentPane().add(lugarEvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, -1));

        jLabel17.setText("Fecha Max Cancelacion:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        getContentPane().add(fechaCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 200, -1));

        jLabel18.setText("Fecha Max Inscripcion: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        fmaxInscr.setText("jTextField5");
        fmaxInscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmaxInscrActionPerformed(evt);
            }
        });
        getContentPane().add(fmaxInscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 200, -1));

        jLabel12.setText("Observaciones:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel19.setText("¿Tiene sobrecupo?");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        boxSobrecupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "si", "no" }));
        boxSobrecupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSobrecupoActionPerformed(evt);
            }
        });
        getContentPane().add(boxSobrecupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        descripcionArea.setColumns(20);
        descripcionArea.setRows(5);
        jScrollPane1.setViewportView(descripcionArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, 70));

        obserArea.setColumns(20);
        obserArea.setRows(5);
        jScrollPane2.setViewportView(obserArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void existeCopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existeCopagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existeCopagoActionPerformed

    private void neventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neventoActionPerformed

    private void veventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veventoActionPerformed

    private void finicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finicioActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        try {

            EventoDAO evdao = new EventoDAO();
            Evento ev = evdao.getEvt();
            TipoDAO tipDao = new TipoDAO();
            Tipo tip = tipDao.getTip();
            
            tip.setK_idtipo(Integer.parseInt(tipoEvt.getText()));
            ev.setK_idtipo(Integer.parseInt(tipoEvt.getText()));
            ev.setN_nombre(nevento.getText());
            ev.setK_evento(Integer.parseInt(idevento.getText()));
            ev.setI_estado("en proceso");
            ev.setN_descripcion(descripcionArea.getText());
            ev.setN_lugar(lugarEvt.getText());
            ev.setF_inicio(finicio.getText());
            ev.setF_cierre(fcierre.getText());
            ev.setF_maxcancel(fechaCancel.getText());

            if (inscripcion.getSelectedIndex() == 0) {
                ev.setI_tieneins("S");
            } else {
                ev.setI_tieneins("N");
            }

            ev.setF_maxins(fmaxInscr.getText());
            ev.setV_total(Integer.parseInt(vevento.getText()));
            ev.setQ_maxpart(Integer.parseInt(numInscr.getText()));
            ev.setO_observaciones(obserArea.getText());
            ev.setF_fin(fcierre.getText());

            if (boxSobrecupo.getSelectedIndex() == 0) {
                ev.setI_sobrecupo("S");
            } else {

                ev.setI_sobrecupo("N");
            }

            evdao.setEvt(ev);

            evdao.AñadirEvento();
            if (existeCopago.getItemAt(existeCopago.getSelectedIndex()) == "si") {
                CopagoCar e = new CopagoCar();
                e.evento = ev;
                e.setVisible(true);
                dispose();
            }
        } catch (CaException ex) {
            Logger.getLogger(CrearEvento.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_crearActionPerformed

    private void numInscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numInscrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numInscrActionPerformed

    private void boxSobrecupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSobrecupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSobrecupoActionPerformed

    private void fmaxInscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmaxInscrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmaxInscrActionPerformed

    private void tipoEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEvtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEvtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asisMax;
    private javax.swing.JComboBox boxSobrecupo;
    private javax.swing.JButton crear;
    private javax.swing.JTextArea descripcionArea;
    private javax.swing.JComboBox existeCopago;
    private javax.swing.JTextField fcierre;
    private javax.swing.JTextField fechaCancel;
    private javax.swing.JTextField finicio;
    private javax.swing.JTextField fmaxInscr;
    private javax.swing.JTextField idevento;
    private javax.swing.JComboBox inscripcion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lugarEvt;
    private javax.swing.JTextField nevento;
    private javax.swing.JTextField numInscr;
    private javax.swing.JTextArea obserArea;
    private javax.swing.JTextField tipoEvt;
    private javax.swing.JTextField vevento;
    // End of variables declaration//GEN-END:variables
}
